version: "3"

services:
  scrapper_tw:
    build: ./scrapperTW/
    container_name: scrapperTW
    links:
      - "redis:redis"
      - "mongo:mongo"
    depends_on:
      - "bot_telegram"
      - "bot_twitter"

  scrapper_codes:
    build: ./scrapperCodes/
    container_name: scrapperCodes
    links:
      - "redis:redis"
      - "mongo:mongo"
    depends_on:
      - "bot_telegram"
      - "bot_twitter"

  scrapper_yt:
    build: ./scrapperYT/
    container_name: scrapperYT
    links:
      - "redis:redis"
      - "mongo:mongo"
    depends_on:
      - "bot_telegram"
      - "bot_twitter"

  bot_telegram:
    build: ./botTelegram/
    container_name: botTelegram
    links:
      - "redis:redis"
      - "mongo:mongo"
  
  bot_twitter:
    build: ./botTwitter/
    container_name: botTwitter
    links:
      - "redis:redis"

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /home/docker/mongo/data/:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

