version: "3"

services:
  scrapper_tw:
    build: ./scrapperTW/
    container_name: scrapperTW
    depends_on:
      - "redis"
      - "mongo"
      - "bot_telegram"
      - "bot_twitter"
    networks:
      - my-network

  scrapper_codes:
    build: ./scrapperCodes/
    container_name: scrapperCodes
    depends_on:
      - "redis"
      - "mongo"
      - "bot_telegram"
      - "bot_twitter"
    networks:
      - my-network

  scrapper_yt:
    build: ./scrapperYT/
    container_name: scrapperYT
    depends_on:
      - "redis"
      - "mongo"
      - "bot_telegram"
      - "bot_twitter"
    networks:
      - my-network

  bot_telegram:
    build: ./botTelegram/
    container_name: botTelegram
    depends_on:
      - "redis"
      - "mongo"
    networks:
      - my-network

  bot_twitter:
    build: ./botTwitter/
    container_name: botTwitter
    depends_on:
      - "redis"
      - "mongo"
    networks:
      - my-network

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /home/docker/mongo/data/:/data/db
    networks:
      - my-network

  redis:
    image: redis
    container_name: redis
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

